repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
        exclude: ^.devcontainer/devcontainer.json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        exclude: docker-compose.yml
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: no-commit-to-branch
      - id: pretty-format-json
        exclude: ^.devcontainer/devcontainer.json
        args: [--no-sort-keys]
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.12.9"
    hooks:
      - id: ruff-check
      - id: ruff-format

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
